[package]
org = "luheerathan"
name = "maven_adapter"
version = "0.1.0"
distribution = "2201.12.11"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "net.lingala.zip4j"
artifactId = "zip4j"
version = "2.10.0"
